; generated by Slic3r 0.9.3 on 2012-10-30 at 20:35:33

; layer_height = 0.3
; perimeters = 3
; solid_layers = 3
; fill_density = 0.4
; perimeter_speed = 40
; infill_speed = 15%
; travel_speed = 100
; scale = 1
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; single wall width = 0.70mm

